# Generated by Django 4.2.7 on 2026-03-08 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('colegio_abogados', models.CharField(blank=True, max_length=200)),
                ('matricula_tomo', models.CharField(blank=True, max_length=50, verbose_name='Tomo')),
                ('matricula_folio', models.CharField(blank=True, max_length=50, verbose_name='Folio')),
                ('matricula_numero', models.CharField(blank=True, max_length=50, verbose_name='Número de matrícula')),
                ('numero_jubilacion', models.CharField(blank=True, max_length=50)),
                ('cuil_cuit', models.CharField(blank=True, max_length=20)),
                ('condicion_fiscal', models.CharField(choices=[('monotributista', 'Monotributista'), ('responsable_inscripto', 'Responsable Inscripto'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor Final')], default='monotributista', max_length=30)),
                ('domicilio_real', models.TextField(blank=True)),
                ('domicilio_electronico', models.EmailField(blank=True, max_length=254)),
                ('firma_digital', models.FileField(blank=True, null=True, upload_to='firmas/')),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
