# Generated by Django 4.2.7 on 2026-06-02 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_mev_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 2, 12, 18, 43, 423401)),
            preserve_default=False,
        ),
    ]
