# Generated by Django 4.2.7 on 2026-07-24 15:39

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_perfilusuario_mev_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='dashboard_umbrales',
            field=models.JSONField(blank=True, default=apps.usuarios.models.default_dashboard_umbrales, verbose_name='Umbrales de las tarjetas del dashboard'),
        ),
    ]
