# Generated by Django 4.2.7 on 2026-06-16 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('trial', 'Trial'), ('activo', 'Activo'), ('moroso', 'Moroso'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='trial', max_length=20)),
                ('trial_hasta', models.DateField()),
                ('mp_preapproval_id', models.CharField(blank=True, max_length=100)),
                ('mp_payer_email', models.EmailField(blank=True, max_length=254)),
                ('proximo_cobro', models.DateField(blank=True, null=True)),
                ('ultimo_cobro', models.DateField(blank=True, null=True)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
                ('afip_cae', models.CharField(blank=True, max_length=50)),
                ('afip_cae_vto', models.DateField(blank=True, null=True)),
                ('factura_numero', models.CharField(blank=True, max_length=20)),
                ('factura_pdf_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='billing.suscripcion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('cuit', models.CharField(blank=True, max_length=13)),
                ('condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('monotributo', 'Monotributista'), ('consumidor_final', 'Consumidor Final'), ('exento', 'Exento')], default='consumidor_final', max_length=20)),
                ('domicilio', models.CharField(blank=True, max_length=300)),
                ('email_facturacion', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_facturacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
