# Generated by Django 4.2.7 on 2026-06-20 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpetas', '0017_alter_carpeta_mev_url'),
        ('movimientos', '0024_movimiento_fecha_completado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionMEVRecibida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('remitente', models.CharField(blank=True, max_length=255)),
                ('asunto', models.CharField(blank=True, max_length=500)),
                ('fecha_recepcion', models.DateTimeField()),
                ('organismo', models.CharField(blank=True, max_length=255)),
                ('nro_causa', models.CharField(blank=True, max_length=50)),
                ('caratula', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_proveido', models.DateTimeField(blank=True, null=True)),
                ('cuerpo_proveido', models.TextField(blank=True)),
                ('estado_procesamiento', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('sin_match', 'Sin match'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('raw_html', models.TextField(blank=True)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_mev_recibidas', to='carpetas.carpeta')),
                ('movimiento_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_mev_origen', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'Notificación MEV Recibida',
                'verbose_name_plural': 'Notificaciones MEV Recibidas',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
