# Generated by Django 4.2.7 on 2026-07-02 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mev_ingest', '0002_notificacionmevrecibida_carpetas_candidatas_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionmevrecibida',
            name='destinatario',
            field=models.CharField(blank=True, help_text='Email del abogado destinatario original del mail (antes del reenvío a la casilla compartida).', max_length=255),
        ),
        migrations.AddField(
            model_name='notificacionmevrecibida',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text="Abogado dueño de la notificación, identificado por 'destinatario'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_mev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacionmevrecibida',
            name='estado_procesamiento',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('sin_match', 'Sin match'), ('procesado', 'Procesado'), ('error', 'Error'), ('no_reconocido', 'No reconocido')], default='pendiente', max_length=20),
        ),
    ]
