# Generated by Django 4.2.7 on 2026-05-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organismos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismo',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organismo',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organismo',
            name='materia',
            field=models.CharField(blank=True, choices=[('civil_comercial', 'Civil y Comercial'), ('laboral', 'Laboral'), ('familia', 'Familia'), ('penal', 'Penal')], max_length=50),
        ),
        migrations.AddField(
            model_name='organismo',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
