# Generated by Django 4.2.7 on 2026-03-03 22:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha_movimiento']},
        ),
        migrations.AlterModelOptions(
            name='tipomovimiento',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.RenameField(
            model_name='movimiento',
            old_name='vencimiento',
            new_name='fecha_vencimiento',
        ),
        migrations.RenameField(
            model_name='movimiento',
            old_name='fecha_modificacion',
            new_name='ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='tiempo_trabajo',
        ),
        migrations.RemoveField(
            model_name='tipomovimiento',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='tipomovimiento',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='tipomovimiento',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='tipomovimiento',
            name='icono',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_movimiento',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 3, 22, 30, 33, 37210, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_acto',
            field=models.CharField(choices=[('escrito', 'Escrito'), ('proveido', 'Proveído'), ('resolucion', 'Resolución'), ('sentencia', 'Sentencia'), ('notificacion', 'Notificación'), ('otro', 'Otro')], default='escrito', max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='vencido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='movimientos.tipomovimiento'),
        ),
        migrations.AlterField(
            model_name='tipomovimiento',
            name='descripcion',
            field=models.TextField(blank=True, default=datetime.datetime(2026, 3, 3, 22, 32, 19, 602195, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipomovimiento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
