# Generated by Django 4.2.7 on 2026-03-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_alter_movimiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#4FC3F7', max_length=7)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de Movimiento',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha_movimiento'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='tipomovimiento',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de Movimiento'},
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='tipo_acto',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_notificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tiempo_trabajo',
            field=models.IntegerField(blank=True, help_text='Tiempo de trabajo en minutos', null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='movimientos.estadomovimiento', verbose_name='Estado'),
        ),
    ]
