# Generated by Django 4.2.7 on 2026-05-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_estadomovimiento_alter_movimiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_cambio_estado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
