# Generated by Django 4.2.7 on 2026-05-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
        ('movimientos', '0004_add_fecha_cambio_estado_to_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='carpetas.carpeta'),
        ),
    ]
