# Generated by Django 4.2.7 on 2026-06-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0021_movimiento_transcripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionsistema',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Asignación de movimiento'), ('cambio_estado', 'Cambio de estado'), ('carpeta_compartida', 'Carpeta compartida'), ('mev_nuevo_movimiento', 'Nuevo movimiento MEV'), ('mev_cambio_estado', 'Cambio de estado MEV'), ('mev_error', 'Error de sincronización MEV')], max_length=20),
        ),
    ]
