# Generated by Django 4.2.7 on 2026-07-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0024_movimiento_fecha_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='movimientos.tipomovimiento'),
        ),
    ]
