# Generated by Django 4.2.7 on 2026-02-23 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organismos', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la carpeta', max_length=200)),
                ('caratula_generada', models.BooleanField(default=False, help_text='Si se generó automáticamente')),
                ('parte', models.CharField(choices=[('cliente', 'Cliente'), ('contraparte', 'Contraparte'), ('otro', 'Otro')], default='cliente', max_length=20)),
                ('contraparte', models.CharField(blank=True, max_length=200)),
                ('numero_expediente', models.CharField(blank=True, max_length=50)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#4FC3F7', help_text='Color en HEX', max_length=7)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de Carpeta',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ObjetoCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Objeto de Carpeta',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Carpeta',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CompartirCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compartido', models.DateTimeField(auto_now_add=True)),
                ('puede_editar', models.BooleanField(default=False)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos', to='carpetas.carpeta')),
                ('compartido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpetas_compartidas_por', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('carpeta', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='carpeta',
            name='compartida_con',
            field=models.ManyToManyField(blank=True, related_name='carpetas_compartidas', through='carpetas.CompartirCarpeta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='carpetas.estadocarpeta'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='objeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='carpetas.objetocarpeta'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organismos.organismo'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carpetas_propias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='carpetas.tipocarpeta'),
        ),
    ]
