# Generated by Django 4.2.7 on 2026-05-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='es_publico',
            field=models.BooleanField(default=False, help_text='Visible para todos los usuarios autenticados'),
        ),
    ]
