# Generated by Django 4.2.7 on 2026-05-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0002_add_es_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='parte',
            field=models.CharField(choices=[('actor', 'Actor'), ('demandado', 'Demandado'), ('otro', 'Otro')], default='actor', max_length=20),
        ),
    ]
