# Generated by Django 4.2.7 on 2026-05-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_fecha_eliminacion'),
        ('carpetas', '0004_carpeta_fecha_eliminacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente/Parte'), ('contraparte', 'Contraparte')], max_length=20)),
                ('nombre_manual', models.CharField(blank=True, max_length=200)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='carpetas.carpeta')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.persona')),
            ],
            options={
                'ordering': ['tipo', 'id'],
            },
        ),
    ]
