# Generated by Django 4.2.7 on 2026-06-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0016_backfill_mev_primera_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='mev_url',
            field=models.URLField(blank=True, help_text='Enlace al expediente en la MEV (se abre manualmente)', max_length=500),
        ),
    ]
